### ISSUE TITLE
Luci Network -> Wifi -> Scan does not work

### ISSUE THREAD

**Issue by Lukse** [8devices/luci#3]
After completing this (http://www.8devices.com/wiki_carambola/doku.php/carambola_luci) tutorial, there some issues with WiFi configuration from LuCi.

Enabled and configured WiFi for STA mode.

After logging to LuCi http page Network -> Wifi -> Scan yields this error:

/usr/lib/lua/luci/dispatcher.lua:449: Failed to execute call dispatcher target for entry '/admin/network/wireless_join'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:105: Failed to execute template 'admin_network/wifi_join'.
A runtime error occured: [string "/usr/lib/lua/luci/view/admin_network/wifi_j..."]:69: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
    [C]: in function 'assert'
    /usr/lib/lua/luci/dispatcher.lua:449: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:195: in function

**Comment by 8devices** [comment]
It's 7 month old code. Can you please try replacing:

```
src-git luci https://github.com/8devices/luci.git
```

with

```
src-git git://nbd.name/luci.git
```

And try then if the same Lua excepction is showing up ?

**Comment by Lukse** [comment]
Looks better. Will update wiki.

**Comment by Lukse** [comment]
Although no scan results being displayed.

**Comment by valinskas** [comment]
Wireless scan works here. I don't see distorted scan results either. 

You can try this firmware:
http://pkg.8devices.com/v2.3/carambola/openwrt-ramips-rt305x-carambola-squashfs-sysupgrade.bin

Firmware has bootstrap theme compiled in.  So GUI  should just work out of the box.

**Comment by valinskas** [comment]
It works for me here, closing.
